In [1]:
import pandas as pd
import numpy as np

In [2]:
mabc = pd.read_csv('data/monthly_arrivals_by_country_filtered.csv')

In [3]:
fsi = pd.read_csv("data/fragilestatesindex_joined.csv")

In [4]:
PSQ_TMS = pd.read_csv("data/PSQ_TMS.csv", skiprows=range(5), na_values="*")

In [5]:
test = PSQ_TMS[PSQ_TMS["Origin / Returned from"] == "Iraq"][PSQ_TMS["Population type"] != "Returned refugees"]

/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:1997: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "DataFrame index.", UserWarning)

In [6]:
gdp_clean = pd.read_csv("data/world_bank_gdp/GDP_filtered.csv")

In [7]:
gdp_info_raw = pd.read_csv("data/world_bank_gdp/GDP_2011-2015.csv",skiprows=4)

In [8]:
pov_raw = pd.read_csv("data/world_bank_poverty/Poverty_raw.csv", skiprows=4)

In [9]:
# Create annualized dataset specifically for Iraq
gdp = gdp_info_raw[gdp_info_raw["Country Name"] == "Iraq"].transpose()[4:-1]
gdp.columns = ["GDP"]
gdp.index = pd.to_numeric(gdp.index)
gdp.index.name = "Year"
gdp["GDP"] = pd.to_numeric(gdp["GDP"])
gdp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56 entries, 1960 to 2015
Data columns (total 1 columns):
GDP    25 non-null float64
dtypes: float64(1)
memory usage: 896.0 bytes

In [10]:
ged40 = pd.read_csv("data/UDCP/ged40.csv")
ged40

,id,relid,year,active_year,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,dyad_new_id,...,date_prec,date_start,date_end,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best_est,high_est,low_est
0,4,YEM-2010-1-784-46,2010,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2010-09-25,2010-09-25,2,0,0,0,2,2,2
1,5,YEM-2011-3-678-28,2011,1,3,678,715,Government of Yemen (North Yemen) - Civilians,678,1182,...,1,2011-02-19,2011-02-19,0,0,0,0,0,2,0
2,6,YEM-2011-1-784-30,2011,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2011-04-16,2011-04-16,0,0,0,0,0,1,0
3,7,YEM-2012-1-784-161,2012,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2012-06-04,2012-06-04,4,1,0,0,5,5,5
4,10,YEM-2012-1-784-254,2012,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2012-12-09,2012-12-09,0,4,1,0,5,5,5
5,13,YEM-2011-1-784-29,2011,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2011-04-11,2011-04-11,0,0,0,0,0,13,0
6,14,YEM-1994-1-375-53.1,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,1,1994-06-08,1994-06-08,0,0,0,0,0,50,0
7,16,YEM-1994-1-375-5,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,2,1994-02-21,1994-02-24,0,0,0,10,10,10,10
8,18,YEM-1994-1-375-21,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,1,1994-05-09,1994-05-09,0,0,0,0,0,1,0
9,19,YEM-2010-1-784-19,2010,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2010-06-12,2010-06-12,1,0,0,0,1,1,1
10,20,YEM-2011-1-784-130,2011,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2011-09-07,2011-09-07,8,14,1,0,23,23,23
11,21,YEM-2010-1-784-30,2010,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2010-08-21,2010-08-21,0,7,0,0,7,7,7
12,22,YEM-2010-1-784-23,2010,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2010-07-22,2010-07-22,5,0,0,0,5,5,5
13,23,YEM-2011-1-784-53,2011,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2011-06-04,2011-06-04,6,0,0,0,6,6,6
14,24,YEM-2011-1-784-54,2011,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2011-06-04,2011-06-04,3,0,0,0,3,3,3
15,25,YEM-2009-1-784-3,2009,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2009-12-17,2009-12-17,0,14,41,0,55,59,55
16,27,YEM-2012-1-784-198,2012,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2012-06-30,2012-06-30,0,2,0,0,2,2,2
17,28,YEM-1994-1-375-49,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,2,1994-06-05,1994-06-06,0,0,0,3,3,10,3
18,29,YEM-1994-1-375-61,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,1,1994-06-17,1994-06-17,0,0,0,4,4,4,4
19,32,YEM-1994-1-375-62,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,2,1994-06-16,1994-06-18,0,0,0,0,0,9,0
20,34,YEM-2010-1-784-5,2010,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2010-01-19,2010-01-19,0,1,0,0,1,1,1
21,35,YEM-2012-1-784-106,2012,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2012-05-03,2012-05-03,0,5,0,0,5,5,5
22,36,YEM-2012-1-784-130,2012,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2012-05-15,2012-05-15,0,12,0,0,12,12,12
23,37,YEM-2012-1-784-105,2012,1,1,1-33,230,Yemen (North Yemen):Government,784,459,...,1,2012-05-03,2012-05-03,0,4,0,0,4,4,4
24,38,YEM-1994-1-375-43,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,1,1994-06-02,1994-06-02,0,0,0,2,2,2,2
25,39,YEM-1994-1-375-64,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,1,1994-06-18,1994-06-18,0,0,0,20,20,20,20
26,42,YEM-1994-1-375-57,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,1,1994-06-13,1994-06-13,0,0,10,0,10,10,10
27,43,YEM-1994-1-375-58,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,2,1994-06-13,1994-06-14,0,0,3,0,3,3,3
28,45,YEM-1994-1-375-66,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,2,1994-06-19,1994-06-20,0,0,0,18,18,18,18
29,46,YEM-1994-1-375-70,1994,1,1,1-207,402,Yemen (North Yemen):South Yemen,375,853,...,2,1994-06-21,1994-06-22,0,0,0,11,11,11,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109118,197441,GEO-2008-1-297-485,2008,1,1,1-198,393,Georgia:South Ossetia,297,840,...,2,2008-08-08,2008-08-12,0,0,0,29,29,250,29
109119,197442,GEO-2008-1-297-481,2008,1,1,1-198,393,Georgia:South Ossetia,297,840,...,1,2008-10-03,2008-10-03,0,0,0,0,0,11,0
109120,197446,GEO-2008-1-297-486,2008,1,1,1-198,393,Georgia:South Ossetia,297,840,...,2,2008-08-08,2008-08-12,0,0,0,49,49,49,49
109121,198592,VEN-2005-3-101-0,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-01-09,2005-01-09,0,0,1,0,1,1,1
109122,204488,VEN-2005-3-101-5,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-01-31,2005-01-31,0,0,1,0,1,1,1
109123,204490,VEN-2005-3-101-6,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-02-01,2005-02-01,0,0,1,0,1,1,1
109124,204491,VEN-2005-3-101-7,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-02-12,2005-02-12,0,0,0,0,0,1,0
109125,204493,VEN-2005-3-101-8,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-02-15,2005-02-15,0,0,1,0,1,1,1
109126,204494,VEN-2005-3-101-9,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-02-26,2005-02-26,0,0,0,0,0,1,0
109127,204495,VEN-2005-3-101-10,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-03-10,2005-03-10,0,0,1,0,1,1,1
109128,204496,VEN-2005-3-101-11,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-04-05,2005-04-05,0,0,0,0,0,1,0
109129,204497,VEN-2005-3-101-12,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-04-05,2005-04-05,0,0,0,0,0,1,0
109130,204516,VEN-2005-3-101-13,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-04-20,2005-04-20,0,0,3,0,3,3,3
109131,204518,VEN-2005-3-101-14,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-05-11,2005-05-11,0,0,1,0,1,1,1
109132,204521,VEN-2005-3-101-15,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-06-03,2005-06-03,0,0,1,0,1,1,1
109133,204522,VEN-2005-3-101-16,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-06-08,2005-06-08,0,0,0,0,0,1,0
109134,204523,VEN-2005-3-101-17,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-06-23,2005-06-23,0,0,11,0,11,11,0
109135,204524,VEN-2005-3-101-18,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-07-14,2005-07-14,0,0,1,0,1,1,1
109136,204525,VEN-2005-3-101-19,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-07-30,2005-07-30,0,0,0,0,0,1,0
109137,204527,VEN-2005-3-101-20,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-08-07,2005-08-07,0,0,0,0,0,1,0
109138,204528,VEN-2005-3-101-21,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-08-20,2005-08-20,0,0,1,0,1,1,1
109139,204531,VEN-2005-3-101-22,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-09-07,2005-09-07,0,0,0,0,0,1,0
109140,204532,VEN-2005-3-101-23,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-09-08,2005-09-08,0,0,0,0,0,1,0
109141,204533,VEN-2005-3-101-24,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-09-17,2005-09-17,0,0,1,0,1,1,1
109142,204535,VEN-2005-3-101-25,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-10-01,2005-10-01,0,0,0,0,0,1,0
109143,204536,VEN-2005-3-101-26,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-10-22,2005-10-22,0,0,1,0,1,1,1
109144,204538,VEN-2005-3-101-27,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-11-25,2005-11-25,0,0,1,0,1,1,1
109145,204539,VEN-2005-3-101-28,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-11-25,2005-11-25,0,0,1,0,1,1,1
109146,204540,VEN-2005-3-101-29,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-11-29,2005-11-29,0,0,0,0,0,1,0
109147,204542,VEN-2005-3-101-30,2005,1,3,101,447,Government of Venezuela - Civilians,101,914,...,1,2005-12-09,2005-12-09,0,0,0,0,0,1,0

In [91]:
brd = pd.read_csv("data/UDCP/ucdp-brd-dyadic-2014.csv")
brdi = brd[brd["LocationInc"] == "Iraq"]
brdi = brdi.groupby("Year").sum().drop(["ConflictID","DyadId","SideBID","Incompatibility","TypeOfConflict"],1)
brdi.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19 entries, 1989 to 2014
Data columns (total 3 columns):
BdBest    19 non-null int64
BdLow     19 non-null int64
BdHigh    19 non-null int64
dtypes: int64(3)
memory usage: 608.0 bytes

In [338]:
hcrpsq = pd.read_csv("data/unhcr_popstats_export_time_series_all_data.csv",skiprows=range(2),na_values="*")
#hcrpsq = hcrpsq[hcrpsq["Population type"] != "Returnees"][hcrpsq["Population type"] != "Returned IDPs"]
hcrpsq = hcrpsq[hcrpsq["Population type"] != "Returnees"]
hcrpsq = hcrpsq[hcrpsq["Population type"] != "Returned IDPs"]

fhcrpsq = hcrpsq[hcrpsq["Origin"] == "Iraq"]

rdata = fhcrpsq[fhcrpsq["Population type"] == "Refugees (incl. refugee-like situations)"].groupby('Year').sum() #rdata = fhcrpsq[fhcrpsq["Population type"] != "Persons in Refugee-like situation"].groupby('Year').sum()
rdata.columns = ["Refugees + IDP"]
rdata["Previous Year Refugees"] = rdata["Refugees + IDP"].shift(1)
rdata["Delta Refugees"] = rdata["Refugees + IDP"].shift(2) - rdata["Refugees + IDP"].shift(1)
rdata["4 yr avg Refugees"] = (rdata["Refugees + IDP"].shift(4) + rdata["Refugees + IDP"].shift(3) + rdata["Refugees + IDP"].shift(2) + rdata["Refugees + IDP"].shift(1))/4
rdata.index.name = "Year"
rdata.info()
print hcrpsq["Population type"].unique()

#fhcrpsq

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39 entries, 1968 to 2014
Data columns (total 4 columns):
Refugees + IDP            39 non-null float64
Previous Year Refugees    38 non-null float64
Delta Refugees            37 non-null float64
4 yr avg Refugees         35 non-null float64
dtypes: float64(4)
memory usage: 1.5 KB
['Refugees (incl. refugee-like situations)' 'Internally displaced persons'
 'Others of concern' 'Asylum-seekers' 'Stateless']

In [339]:
unemp = pd.read_csv("data/world_bank_unemployment/API_SL.UEM.TOTL.ZS_DS2_en_csv_v2.csv",
                     skiprows=range(3), 
                     na_values="*"
                   ).set_index("Country Name").transpose()[3:-1][["Iraq"]]
unemp.columns = ["Unemployment"]
unemp.index = unemp.index.astype(np.int64)
unemp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56 entries, 1960 to 2015
Data columns (total 1 columns):
Unemployment    24 non-null object
dtypes: object(1)
memory usage: 896.0+ bytes

In [342]:
cpd = pd.read_table("data/centripetalism.txt")
cpdi = cpd[cpd["Country"] == "Iraq"]
cpdid = cpdi[["Year",
              "GDPpc_imputed_ln_wtradeF",
              "Growthpc_imputed_sd5_wgeoF",
              "IMR_ipolate_ln_wgeoF",
              "Oil_production_MH_pc",
              "Participation_Vanhanen_wgeoF",
              "Polity4_imp_sd5_wgeoF",
              "Schooling_tot_ipo_wgeoF",
              "Stock_depr1",
              "Tax_Revenue_WDI_wgeoF",
              "Trade_WDI_ln_wgeoF"]]
cpdid = cpdid.groupby("Year").sum()
cpdid.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 203 entries, 1800 to 2002
Data columns (total 10 columns):
GDPpc_imputed_ln_wtradeF        51 non-null float64
Growthpc_imputed_sd5_wgeoF      47 non-null float64
IMR_ipolate_ln_wgeoF            42 non-null float64
Oil_production_MH_pc            42 non-null float64
Participation_Vanhanen_wgeoF    99 non-null float64
Polity4_imp_sd5_wgeoF           193 non-null float64
Schooling_tot_ipo_wgeoF         40 non-null float64
Stock_depr1                     103 non-null float64
Tax_Revenue_WDI_wgeoF           32 non-null float64
Trade_WDI_ln_wgeoF              42 non-null float64
dtypes: float64(10)
memory usage: 17.4 KB

In [343]:
concat = rdata.join([gdp,brdi,unemp,cpdid], how="outer")
concat["BdBest"] = concat["BdBest"].fillna(0)
concat["BdLow"] = concat["BdLow"].fillna(0)
concat["BdHigh"] = concat["BdHigh"].fillna(0)
concat

,Refugees + IDP,Previous Year Refugees,Delta Refugees,4 yr avg Refugees,GDP,BdBest,BdLow,BdHigh,Unemployment,GDPpc_imputed_ln_wtradeF,Growthpc_imputed_sd5_wgeoF,IMR_ipolate_ln_wgeoF,Oil_production_MH_pc,Participation_Vanhanen_wgeoF,Polity4_imp_sd5_wgeoF,Schooling_tot_ipo_wgeoF,Stock_depr1,Tax_Revenue_WDI_wgeoF,Trade_WDI_ln_wgeoF
1800,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1801,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1802,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1803,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1804,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1805,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1806,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1807,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1808,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000352,NaN,NaN,NaN,NaN
1809,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000431,NaN,NaN,NaN,NaN
1810,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000431,NaN,NaN,NaN,NaN
1811,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000427,NaN,NaN,NaN,NaN
1812,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000157,NaN,NaN,NaN,NaN
1813,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000620,NaN,NaN,NaN,NaN
1814,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000696,NaN,NaN,NaN,NaN
1815,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000567,NaN,NaN,NaN,NaN
1816,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000463,NaN,NaN,NaN,NaN
1817,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1818,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1819,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000519,NaN,NaN,NaN,NaN
1820,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000636,NaN,NaN,NaN,NaN
1821,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000636,NaN,NaN,NaN,NaN
1822,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000509,NaN,NaN,NaN,NaN
1823,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000255,NaN,NaN,NaN,NaN
1824,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000377,NaN,NaN,NaN,NaN
1825,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000399,NaN,NaN,NaN,NaN
1826,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000232,NaN,NaN,NaN,NaN
1827,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000232,NaN,NaN,NaN,NaN
1828,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000191,NaN,NaN,NaN,NaN
1829,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000479,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1986,400745,401503,-299779,177678.50,NaN,0,0,0,NaN,8.409665,0.154913,0.184129,0.107405,1.152295,0.019278,0.146885,-301.1231,0.511706,0.151021
1987,410818,400745,758,251923.25,NaN,0,0,0,NaN,8.607109,0.164279,0.182151,0.127195,1.142453,0.023899,0.149855,-307.1118,0.534723,0.153329
1988,508468,410818,-10073,328697.50,NaN,0,0,0,NaN,8.876632,0.182924,0.180673,0.159586,1.148658,0.035557,0.152824,-313.0407,0.512629,0.161299
1989,507986,508468,-97650,430383.50,NaN,50,50,50,NaN,8.893493,0.167798,0.181140,0.165562,1.136080,0.062088,0.156506,-318.9103,0.519823,0.194088
1990,1133805,507986,482,457004.25,2.012732e+11,94,94,94,NaN,8.185385,0.178553,0.181788,0.115451,1.590030,0.099595,0.156410,-324.7212,0.537254,0.197503
1991,1321853,1133805,-625819,640269.25,7.236353e+10,781,781,1237,19.8,8.330584,0.213205,0.185536,0.015950,1.594857,0.114559,0.158499,-330.4740,0.563880,0.203976
1992,1343824,1321853,-188048,868028.00,9.594840e+10,306,306,793,19.8,7.920707,0.232426,0.185082,0.024831,1.624476,0.109043,0.160588,-336.1693,0.604294,0.210876
1993,771077,1343824,-21971,1076867.00,1.250110e+11,75,75,203,19.7,7.977823,0.208703,0.183564,0.024869,1.664123,0.085615,0.162677,-341.8076,0.673986,0.223845
1994,749834,771077,572747,1142639.75,1.298296e+11,25,25,36,19.5,8.036619,0.254260,0.181487,0.026497,1.664102,0.045695,0.167851,-347.3895,0.684795,0.218803
1995,718719,749834,21243,1046647.00,1.325820e+11,587,587,862,19.4,8.241329,0.231926,0.179618,0.027055,1.743828,0.041179,0.170002,-352.9156,0.669662,0.220250
1996,714730,718719,31115,895863.50,1.471936e+11,398,398,432,19.3,8.619635,0.244163,0.178136,0.027979,1.741668,0.043953,0.172153,-358.3864,0.706125,0.222974
1997,707338,714730,3989,738590.00,1.784545e+11,0,0,0,17.6,8.765377,0.199881,0.176239,0.053865,1.721610,0.042159,0.174304,-363.8026,0.656906,0.217342
1998,675030,707338,7392,722655.25,2.406585e+11,0,0,0,19.2,8.824955,0.180407,0.174102,0.096435,NaN,0.047855,0.176455,-369.1645,0.576031,0.215957
1999,642886,675030,32308,703954.25,2.829717e+11,0,0,0,18.1,8.976245,0.176417,0.172924,0.111325,NaN,0.047996,NaN,-374.4729,0.420348,0.214180
2000,526179,642886,32144,684996.00,2.869517e+11,0,0,0,18.2,NaN,0.161343,0.175042,0.110739,NaN,0.030300,NaN,-379.7281,0.336783,0.189720
2001,530511,526179,116707,637858.25,2.935668e+11,0,0,0,18.2,NaN,NaN,NaN,0.101630,NaN,0.024306,NaN,-375.9309,NaN,NaN
2002,422512,530511,-4332,593651.50,2.733102e+11,0,0,0,18.4,NaN,NaN,NaN,NaN,NaN,0.018109,NaN,-372.1716,NaN,NaN
2003,368580,422512,107999,530522.00,1.828422e+11,0,0,0,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004,311890,368580,53932,461945.50,2.818655e+11,4094,4081,6142,28.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005,262299,311890,56690,408373.25,2.942693e+11,2608,2542,3563,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006,1450905,262299,49591,341320.25,3.241618e+11,3934,3195,4134,17.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007,2309245,1450905,-1188606,598418.50,3.286274e+11,2212,2040,2481,16.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008,1903519,2309245,-858340,1083584.75,3.556672e+11,2112,2098,2539,15.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009,1785212,1903519,405726,1481492.00,3.676863e+11,1036,926,1074,15.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,1683579,1785212,118307,1862220.25,3.912277e+11,1015,836,1060,15.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011,1428308,1683579,101633,1920388.75,4.207515e+11,864,737,959,15.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012,746206,1428308,255271,1700154.50,4.793893e+11,565,487,598,15.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013,401466,746206,682102,1410826.25,5.108955e+11,1870,1723,1924,15.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014,369850,401466,344740,1064889.75,5.000734e+11,12598,12537,14126,16.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [344]:
from sklearn.cross_validation import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import Imputer
from sklearn.svm import LinearSVR
from sklearn import ensemble
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
from sklearn.pipeline import Pipeline

In [345]:
cpruned = concat[np.isfinite(concat["Refugees + IDP"])][13:]

features = cpruned[["Previous Year Refugees",
                    "Delta Refugees", 
                    "4 yr avg Refugees", 
                    "GDP",
                    "BdBest",
                  "Participation_Vanhanen_wgeoF",
                  "Schooling_tot_ipo_wgeoF",
                  "Tax_Revenue_WDI_wgeoF",
                  "Trade_WDI_ln_wgeoF"]]
target = cpruned["Refugees + IDP"]

cpruned

,Refugees + IDP,Previous Year Refugees,Delta Refugees,4 yr avg Refugees,GDP,BdBest,BdLow,BdHigh,Unemployment,GDPpc_imputed_ln_wtradeF,Growthpc_imputed_sd5_wgeoF,IMR_ipolate_ln_wgeoF,Oil_production_MH_pc,Participation_Vanhanen_wgeoF,Polity4_imp_sd5_wgeoF,Schooling_tot_ipo_wgeoF,Stock_depr1,Tax_Revenue_WDI_wgeoF,Trade_WDI_ln_wgeoF
1989,507986,508468,-97650,430383.50,NaN,50,50,50,NaN,8.893493,0.167798,0.181140,0.165562,1.136080,0.062088,0.156506,-318.9103,0.519823,0.194088
1990,1133805,507986,482,457004.25,2.012732e+11,94,94,94,NaN,8.185385,0.178553,0.181788,0.115451,1.590030,0.099595,0.156410,-324.7212,0.537254,0.197503
1991,1321853,1133805,-625819,640269.25,7.236353e+10,781,781,1237,19.8,8.330584,0.213205,0.185536,0.015950,1.594857,0.114559,0.158499,-330.4740,0.563880,0.203976
1992,1343824,1321853,-188048,868028.00,9.594840e+10,306,306,793,19.8,7.920707,0.232426,0.185082,0.024831,1.624476,0.109043,0.160588,-336.1693,0.604294,0.210876
1993,771077,1343824,-21971,1076867.00,1.250110e+11,75,75,203,19.7,7.977823,0.208703,0.183564,0.024869,1.664123,0.085615,0.162677,-341.8076,0.673986,0.223845
1994,749834,771077,572747,1142639.75,1.298296e+11,25,25,36,19.5,8.036619,0.254260,0.181487,0.026497,1.664102,0.045695,0.167851,-347.3895,0.684795,0.218803
1995,718719,749834,21243,1046647.00,1.325820e+11,587,587,862,19.4,8.241329,0.231926,0.179618,0.027055,1.743828,0.041179,0.170002,-352.9156,0.669662,0.220250
1996,714730,718719,31115,895863.50,1.471936e+11,398,398,432,19.3,8.619635,0.244163,0.178136,0.027979,1.741668,0.043953,0.172153,-358.3864,0.706125,0.222974
1997,707338,714730,3989,738590.00,1.784545e+11,0,0,0,17.6,8.765377,0.199881,0.176239,0.053865,1.721610,0.042159,0.174304,-363.8026,0.656906,0.217342
1998,675030,707338,7392,722655.25,2.406585e+11,0,0,0,19.2,8.824955,0.180407,0.174102,0.096435,NaN,0.047855,0.176455,-369.1645,0.576031,0.215957
1999,642886,675030,32308,703954.25,2.829717e+11,0,0,0,18.1,8.976245,0.176417,0.172924,0.111325,NaN,0.047996,NaN,-374.4729,0.420348,0.214180
2000,526179,642886,32144,684996.00,2.869517e+11,0,0,0,18.2,NaN,0.161343,0.175042,0.110739,NaN,0.030300,NaN,-379.7281,0.336783,0.189720
2001,530511,526179,116707,637858.25,2.935668e+11,0,0,0,18.2,NaN,NaN,NaN,0.101630,NaN,0.024306,NaN,-375.9309,NaN,NaN
2002,422512,530511,-4332,593651.50,2.733102e+11,0,0,0,18.4,NaN,NaN,NaN,NaN,NaN,0.018109,NaN,-372.1716,NaN,NaN
2003,368580,422512,107999,530522.00,1.828422e+11,0,0,0,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004,311890,368580,53932,461945.50,2.818655e+11,4094,4081,6142,28.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005,262299,311890,56690,408373.25,2.942693e+11,2608,2542,3563,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006,1450905,262299,49591,341320.25,3.241618e+11,3934,3195,4134,17.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007,2309245,1450905,-1188606,598418.50,3.286274e+11,2212,2040,2481,16.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008,1903519,2309245,-858340,1083584.75,3.556672e+11,2112,2098,2539,15.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009,1785212,1903519,405726,1481492.00,3.676863e+11,1036,926,1074,15.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,1683579,1785212,118307,1862220.25,3.912277e+11,1015,836,1060,15.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011,1428308,1683579,101633,1920388.75,4.207515e+11,864,737,959,15.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012,746206,1428308,255271,1700154.50,4.793893e+11,565,487,598,15.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013,401466,746206,682102,1410826.25,5.108955e+11,1870,1723,1924,15.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014,369850,401466,344740,1064889.75,5.000734e+11,12598,12537,14126,16.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [346]:
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
features_filled = imp.fit_transform(features)


features_train, features_test, target_train, target_test = train_test_split(features_filled, target, test_size=0.2, random_state=198902423)

min_max_scaler = preprocessing.MinMaxScaler()

features_train_mm = min_max_scaler.fit_transform(features_train)
features_test_mm = min_max_scaler.transform(features_test)

clf = ensemble.AdaBoostRegressor(random_state=0, n_estimators=80)

clf.fit(features_train_mm,target_train)

prediction = clf.predict(features_test_mm)

rm = np.sqrt(metrics.mean_squared_error(target_test,prediction))

print rm

print 1 - rm / np.mean(target_test)
pd.DataFrame(zip(features_test, target_test, prediction, (target_test - prediction)/target_test))

499858.977782
0.561150533346

,0,1,2,3
0,"[1450905.0, -1188606.0, 598418.5, 328627420736...",2309245,1343824.000000,0.418068
1,"[1785212.0, 118307.0, 1862220.25, 391227650167...",1683579,1428308.000000,0.151624
2,"[508468.0, -97650.0, 430383.5, 275902870479.0,...",507986,1133805.000000,-1.231961
3,"[1133805.0, -625819.0, 640269.25, 72363526905....",1321853,1186309.750000,0.102540
4,"[675030.0, 32308.0, 703954.25, 282971739255.0,...",642886,520644.833333,0.190144
5,"[422512.0, 107999.0, 530522.0, 182842214622.0,...",368580,646048.375000,-0.752804

In [347]:
estimator = Pipeline([("imputer", Imputer(missing_values='NaN',
                                          strategy="mean",
                                          axis=0)),
                      ("adaboost", ensemble.AdaBoostRegressor(random_state=0,
                                                       n_estimators=150))])
score = cross_val_score(estimator, features_train_mm, target_train).mean()

score

-0.47229915305754777

In [348]:
clf.score(features_test_mm,target_test)

0.48962010219440028

In [349]:
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
features_filled = imp.fit_transform(features)


features_train, features_test, target_train, target_test = train_test_split(features_filled, target, test_size=0.2, random_state=198902423)

min_max_scaler = preprocessing.MinMaxScaler()

features_train_mm = min_max_scaler.fit_transform(features_train)
features_test_mm = min_max_scaler.transform(features_test)

clf = ensemble.RandomForestRegressor(random_state=0, n_estimators=80)

clf.fit(features_train_mm,target_train)

prediction = clf.predict(features_test_mm)

rm = np.sqrt(metrics.mean_squared_error(target_test,prediction))

print rm

print 1 - rm / np.mean(target_test)
pd.DataFrame(zip(features_test, target_test, prediction, (target_test - prediction)/target_test))

604759.253748
0.469053697628

,0,1,2,3
0,"[1450905.0, -1188606.0, 598418.5, 328627420736...",2309245,910405.3125,0.605756
1,"[1785212.0, 118307.0, 1862220.25, 391227650167...",1683579,1438842.7125,0.145367
2,"[508468.0, -97650.0, 430383.5, 275902870479.0,...",507986,814766.9625,-0.603916
3,"[1133805.0, -625819.0, 640269.25, 72363526905....",1321853,1138143.5625,0.138979
4,"[675030.0, 32308.0, 703954.25, 282971739255.0,...",642886,587228.6125,0.086574
5,"[422512.0, 107999.0, 530522.0, 182842214622.0,...",368580,584896.3125,-0.586891

In [351]:
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
features_filled = imp.fit_transform(features)


features_train, features_test, target_train, target_test = train_test_split(features_filled, target, test_size=0.2, random_state=198902423)

min_max_scaler = preprocessing.MinMaxScaler()

features_train_mm = min_max_scaler.fit_transform(features_train)
features_test_mm = min_max_scaler.transform(features_test)

clf = ensemble.GradientBoostingClassifier(random_state=0, n_estimators=600,learning_rate=.8)

clf.fit(features_train_mm,target_train)

prediction = clf.predict(features_test_mm)

rm = np.sqrt(metrics.mean_squared_error(target_test,prediction))

print rm

print 1 - rm / np.mean(target_test)
pd.DataFrame(zip(features_test, target_test, prediction, (target_test - prediction)/target_test))

246760.070852
0.783357846317

,0,1,2,3
0,"[1450905.0, -1188606.0, 598418.5, 328627420736...",2309245,1903519,0.175696
1,"[1785212.0, 118307.0, 1862220.25, 391227650167...",1683579,1428308,0.151624
2,"[508468.0, -97650.0, 430383.5, 275902870479.0,...",507986,262299,0.483649
3,"[1133805.0, -625819.0, 640269.25, 72363526905....",1321853,1133805,0.142261
4,"[675030.0, 32308.0, 703954.25, 282971739255.0,...",642886,526179,0.181536
5,"[422512.0, 107999.0, 530522.0, 182842214622.0,...",368580,530511,-0.439337